### ISSUE TITLE
Feature: Shell commands

### ISSUE THREAD

**Issue by tobinstultiens** [openremote/or-satellite#4]
### Description
As a developer, I'd like to be able to send shell commands, in order to convert my nc files.

Also, here are a few points that need to be addressed:

1. Constraint 1:

### Tasks
- [x] Able to send shell commands.
- [x] Able to send shell commands within a docker container.
- [x] Able to install nco with docker.
